### ISSUE TITLE
File Not Found Exception

### ISSUE THREAD

**Issue by vikas-patel** [yellowcath/PhotoMovie#1]
Hey,

I'm getting following exception while creating the video.
I am able to select photos and audios, but when I press 'next' button it shows 'saving video..' for few milli seconds and crashes.

```
10-03 10:04:29.086 24152-24193/com.hw.photomovie E/AndroidRuntime: FATAL EXCEPTION: GLMovieRecorder
    Process: com.hw.photomovie, PID: 24152
    java.lang.RuntimeException: MediaMuxer creation failed
        at record.GLMovieRecorder.prepareEncoder(GLMovieRecorder.java:229)
        at record.GLMovieRecorder.startRecordImpl(GLMovieRecorder.java:98)
        at record.GLMovieRecorder$1$1.run(GLMovieRecorder.java:76)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:163)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.io.FileNotFoundException: /storage/emulated/0/Movies/photo_movie_2018_10_03_10_04_28.mp4: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:455)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:247)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:128)
        at android.media.MediaMuxer.<init>(MediaMuxer.java:145)
        at record.GLMovieRecorder.prepareEncoder(GLMovieRecorder.java:227)
        at record.GLMovieRecorder.startRecordImpl(GLMovieRecorder.java:98) 
        at record.GLMovieRecorder$1$1.run(GLMovieRecorder.java:76) 
        at android.os.Handler.handleCallback(Handler.java:754) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:163) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
     Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Posix.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:187)
        at libcore.io.IoBridge.open(IoBridge.java:441)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:247) 
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:128) 
        at android.media.MediaMuxer.<init>(MediaMuxer.java:145) 
        at record.GLMovieRecorder.prepareEncoder(GLMovieRecorder.java:227) 
        at record.GLMovieRecorder.startRecordImpl(GLMovieRecorder.java:98) 
        at record.GLMovieRecorder$1$1.run(GLMovieRecorder.java:76) 
        at android.os.Handler.handleCallback(Handler.java:754) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:163) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 

```

**Comment by yellowcath** [comment]
It's fixed ,please try  'com.github.yellowcath:PhotoMovie:1.5.5'

**Comment by vikas-patel** [comment]
Hey, that was pretty quick. I will try latest version.

**Comment by vikas-patel** [comment]
Thanks mates!! It worked.
I really liked this library :)
