### ISSUE TITLE
选择图片后，过一会，程序崩溃，并且我的桌面也重新加载了

### ISSUE THREAD

**Issue by jp1017** [yellowcath/PhotoMovie#8]
```
2018-11-01 14:57:17.240 25828-25828/com.hw.photomovie E/MediaPlayer: start called in state 0, mPlayer(0x0)
2018-11-01 14:57:17.259 25828-25828/com.hw.photomovie E/MediaPlayer: start called in state 0, mPlayer(0x0)
2018-11-01 14:57:17.290 25828-25828/com.hw.photomovie E/MediaPlayer: start called in state 0, mPlayer(0x0)
2018-11-01 14:57:17.308 25828-25828/com.hw.photomovie E/MediaPlayer: start called in state 0, mPlayer(0x0)
2018-11-01 14:57:17.340 25828-25828/com.hw.photomovie E/MediaPlayer: start called in state 0, mPlayer(0x0)
2018-11-01 14:57:17.359 25828-25828/com.hw.photomovie E/MediaPlayer: start called in state 0, mPlayer(0x0)
2018-11-01 14:57:17.391 25828-25828/com.hw.photomovie E/MediaPlayer: start called in state 0, mPlayer(0x0)
2018-11-01 14:57:17.425 25828-25828/com.hw.photomovie E/MediaPlayer: start called in state 0, mPlayer(0x0)
2018-11-01 14:57:17.458 25828-25828/com.hw.photomovie E/MediaPlayer: start called in state 0, mPlayer(0x0)
2018-11-01 14:57:17.491 25828-25828/com.hw.photomovie E/MediaPlayer: start called in state 0, mPlayer(0x0)
2018-11-01 14:57:17.509 25828-25828/com.hw.photomovie E/MediaPlayer: start called in state 0, mPlayer(0x0)
2018-11-01 14:57:17.541 25828-25828/com.hw.photomovie E/MediaPlayer: start called in state 0, mPlayer(0x0)
2018-11-01 14:57:17.574 25828-25828/com.hw.photomovie E/MediaPlayer: start called in state 0, mPlayer(0x0)
2018-11-01 14:57:17.608 25828-25828/com.hw.photomovie E/MediaPlayer: start called in state 0, mPlayer(0x0)
2018-11-01 14:57:17.643 25828-25828/com.hw.photomovie E/MediaPlayer: start called in state 0, mPlayer(0x0)
2018-11-01 14:57:17.675 25828-25828/com.hw.photomovie E/MediaPlayer: start called in state 0, mPlayer(0x0)
2018-11-01 14:57:17.708 25828-25828/com.hw.photomovie E/MediaPlayer: start called in state 0, mPlayer(0x0)
2018-11-01 14:57:17.712 3253-3253/? E/VoiceAssistantService: VoiceRecognitionEngineBase : onSpeechUninit destroyService and needLaunchIfly = true
2018-11-01 14:57:17.742 25828-25828/com.hw.photomovie E/MediaPlayer: start called in state 0, mPlayer(0x0)
2018-11-01 14:57:17.775 25828-25828/com.hw.photomovie E/MediaPlayer: start called in state 0, mPlayer(0x0)
2018-11-01 14:57:17.808 25828-25828/com.hw.photomovie E/MediaPlayer: start called in state 0, mPlayer(0x0)
2018-11-01 14:57:17.827 25828-25828/com.hw.photomovie E/MediaPlayer: start called in state 0, mPlayer(0x0)
2018-11-01 14:57:17.858 25828-25828/com.hw.photomovie E/MediaPlayer: start called in state 0, mPlayer(0x0)
2018-11-01 14:57:17.892 25828-25828/com.hw.photomovie E/MediaPlayer: start called in state 0, mPlayer(0x0)
2018-11-01 14:57:17.925 25828-25828/com.hw.photomovie E/MediaPlayer: start called in state 0, mPlayer(0x0)
2018-11-01 14:57:18.180 1669-2057/? E/InputDispatcher: channel '5538979 com.hw.photomovie/com.hw.photomovie.sample.DemoActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2018-11-01 14:57:18.436 532-532/? E/lowmemorykiller: Error opening /proc/24704/oom_score_adj; errno=2
2018-11-01 14:57:18.467 532-532/? E/lowmemorykiller: Error opening /proc/24704/oom_score_adj; errno=2
2018-11-01 14:57:18.522 3253-3253/? E/SpeechServiceUtil: android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:833)
        at com.iflytek.business.speech.ISpeechService$Stub$Proxy.stopSpeak(ISpeechService.java:553)
        at com.iflytek.business.speech.SpeechServiceUtil.stopSpeak(SpeechServiceUtil.java:616)
        at com.smartisanos.voice.engine.XunfeiRecognizerEngine.destroyService(XunfeiRecognizerEngine.java:1186)
        at com.smartisanos.voice.engine.XunfeiRecognizerEngine$1.onSpeechUninit(XunfeiRecognizerEngine.java:181)
        at com.iflytek.business.speech.SpeechServiceUtil$2.handleMessage(SpeechServiceUtil.java:71)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:159)
        at android.app.ActivityThread.main(ActivityThread.java:6364)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)
```

**Comment by yellowcath** [comment]
看日志是内存不足了。
检查了一下发现在demo里反复切换转场动画的话确实会内存泄露，做了一下处理。已更新版本：
 implementation 'com.github.yellowcath:PhotoMovie:1.6.2'
