### ISSUE TITLE
App Crash Android 8.1.0 Color OS v5.0 Realme Device

### ISSUE THREAD

**Issue by VineshChauhan24** [yellowcath/PhotoMovie#9]
i got error

 java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2637)
        at record.GLMovieRecorder.drainEncoderApi21(GLMovieRecorder.java:410)
        at record.GLMovieRecorder.drainEncoder(GLMovieRecorder.java:284)
        at record.GLMovieRecorder.startRecordImpl(GLMovieRecorder.java:121)
        at record.GLMovieRecorder$1$1.run(GLMovieRecorder.java:76)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:187)
        at android.os.HandlerThread.run(HandlerThread.java:65)

app working fine in all device i have tested but getting error in Realme device which has color os v5.0 with android version 8.1.0

**Comment by yellowcath** [comment]
Did you set the background music?

**Comment by VineshChauhan24** [comment]
App Crash when i set Bacground Music too

**Comment by yellowcath** [comment]
implementation 'com.github.yellowcath:PhotoMovie:1.6.3'
Fixed crash of encoder "OMX.MTK.VIDEO.ENCODER.AVC"
the encoder limited max size "1080x1920"
